apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: python-pod-kill-all
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "python-service"
  duration: "40s"



