apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: python-pod-kill-all
  namespace: chaos-testing
spec:
  action: pod-kill
  # mode: all will kill ALL matching pods at the same time
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "python-service"
  # short duration for demo; adjust if you want longer outage
  duration: "20s"
# optional: make sure it is synchronous
  scheduler:
    cron: "@every 1m"
